//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipf.Core.Security.Authorization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ipf.Core.Security.Authorization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid values &apos;{0}&apos;.&quot;.
        /// </summary>
        internal static string AcceptHeaderParser_ParseAcceptHeader_InvalidValues {
            get {
                return ResourceManager.GetString("AcceptHeaderParser_ParseAcceptHeader_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action descriptor must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ActionDescriptorMustBeBasedOnControllerAction {
            get {
                return ResourceManager.GetString("ActionDescriptorMustBeBasedOnControllerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; on type &apos;{1}&apos; returned a Task instance even though it is not an asynchronous method..
        /// </summary>
        internal static string ActionExecutor_UnexpectedTaskInstance {
            get {
                return ResourceManager.GetString("ActionExecutor_UnexpectedTaskInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; on type &apos;{1}&apos; returned an instance of &apos;{2}&apos;. Make sure to call Unwrap on the returned value to avoid unobserved faulted Task..
        /// </summary>
        internal static string ActionExecutor_WrappedTaskInstance {
            get {
                return ResourceManager.GetString("ActionExecutor_WrappedTaskInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action invoker could not be created for action &apos;{0}&apos;..
        /// </summary>
        internal static string ActionInvokerFactory_CouldNotCreateInvoker {
            get {
                return ResourceManager.GetString("ActionInvokerFactory_CouldNotCreateInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return null from an action method with a return type of &apos;{0}&apos;..
        /// </summary>
        internal static string ActionResult_ActionReturnValueCannotBeNull {
            get {
                return ResourceManager.GetString("ActionResult_ActionReturnValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; has ApiExplorer enabled, but is using conventional routing. Only actions which use attribute routing support ApiExplorer..
        /// </summary>
        internal static string ApiExplorer_UnsupportedAction {
            get {
                return ResourceManager.GetString("ApiExplorer_UnsupportedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; are out of bounds for the string..
        /// </summary>
        internal static string Argument_InvalidOffsetLength {
            get {
                return ResourceManager.GetString("Argument_InvalidOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an {0} provides a result value by setting the {1} property of {2} to a non-null value, then it cannot call the next filter by invoking {3}..
        /// </summary>
        internal static string AsyncActionFilter_InvalidShortCircuit {
            get {
                return ResourceManager.GetString("AsyncActionFilter_InvalidShortCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an {0} provides a result value by setting the {1} property of {2} to a non-null value, then it cannot call the next filter by invoking {3}..
        /// </summary>
        internal static string AsyncResourceFilter_InvalidShortCircuit {
            get {
                return ResourceManager.GetString("AsyncResourceFilter_InvalidShortCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an {0} cancels execution by setting the {1} property of {2} to &apos;true&apos;, then it cannot call the next filter by invoking {3}..
        /// </summary>
        internal static string AsyncResultFilter_InvalidShortCircuit {
            get {
                return ResourceManager.GetString("AsyncResultFilter_InvalidShortCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred with attribute routing information:{0}{0}{1}.
        /// </summary>
        internal static string AttributeRoute_AggregateErrorMessage {
            get {
                return ResourceManager.GetString("AttributeRoute_AggregateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}:{1}{2}.
        /// </summary>
        internal static string AttributeRoute_AggregateErrorMessage_ErrorNumber {
            get {
                return ResourceManager.GetString("AttributeRoute_AggregateErrorMessage_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute route &apos;{0}&apos; cannot contain a parameter named &apos;{{{1}}}&apos;. Use &apos;[{1}]&apos; in the route template to insert the value &apos;{2}&apos;..
        /// </summary>
        internal static string AttributeRoute_CannotContainParameter {
            get {
                return ResourceManager.GetString("AttributeRoute_CannotContainParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute routes with the same name &apos;{0}&apos; must have the same template:{1}{2}.
        /// </summary>
        internal static string AttributeRoute_DuplicateNames {
            get {
                return ResourceManager.GetString("AttributeRoute_DuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: &apos;{0}&apos; - Template: &apos;{1}&apos;.
        /// </summary>
        internal static string AttributeRoute_DuplicateNames_Item {
            get {
                return ResourceManager.GetString("AttributeRoute_DuplicateNames_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For action: &apos;{0}&apos;{1}Error: {2}.
        /// </summary>
        internal static string AttributeRoute_IndividualErrorMessage {
            get {
                return ResourceManager.GetString("AttributeRoute_IndividualErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method &apos;{0}&apos; must not define attribute routed actions and non attribute routed actions at the same time:{1}{2}{1}{1}Use &apos;AcceptVerbsAttribute&apos; to create a single route that allows multiple HTTP verbs and defines a route, or set a route template in all attributes that constrain HTTP verbs..
        /// </summary>
        internal static string AttributeRoute_MixedAttributeAndConventionallyRoutedActions_ForMethod {
            get {
                return ResourceManager.GetString("AttributeRoute_MixedAttributeAndConventionallyRoutedActions_ForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: &apos;{0}&apos; - Route Template: &apos;{1}&apos; - HTTP Verbs: &apos;{2}&apos;.
        /// </summary>
        internal static string AttributeRoute_MixedAttributeAndConventionallyRoutedActions_ForMethod_Item {
            get {
                return ResourceManager.GetString("AttributeRoute_MixedAttributeAndConventionallyRoutedActions_ForMethod_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string AttributeRoute_NullTemplateRepresentation {
            get {
                return ResourceManager.GetString("AttributeRoute_NullTemplateRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty replacement token (&apos;[]&apos;) is not allowed..
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_EmptyTokenNotAllowed {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_EmptyTokenNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token delimiters (&apos;[&apos;, &apos;]&apos;) are imbalanced..
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_ImbalancedSquareBrackets {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_ImbalancedSquareBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route template &apos;{0}&apos; has invalid syntax. {1}.
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_InvalidSyntax {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_InvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While processing template &apos;{0}&apos;, a replacement value for the token &apos;{1}&apos; could not be found. Available tokens: &apos;{2}&apos;. To use a &apos;[&apos; or &apos;]&apos; as a literal string in a route or within a constraint, use &apos;[[&apos; or &apos;]]&apos; instead..
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_ReplacementValueNotFound {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_ReplacementValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A replacement token is not closed..
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_UnclosedToken {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_UnclosedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unescaped &apos;[&apos; token is not allowed inside of a replacement token. Use &apos;[[&apos; to escape..
        /// </summary>
        internal static string AttributeRoute_TokenReplacement_UnescapedBraceInToken {
            get {
                return ResourceManager.GetString("AttributeRoute_TokenReplacement_UnescapedBraceInToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} cannot be created without a valid instance of {1}..
        /// </summary>
        internal static string AuthorizeFilter_AuthorizationPolicyCannotBeCreated {
            get {
                return ResourceManager.GetString("AuthorizeFilter_AuthorizationPolicyCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must implement &apos;{1}&apos; to be used as a model binder..
        /// </summary>
        internal static string BinderType_MustBeIModelBinder {
            get {
                return ResourceManager.GetString("BinderType_MustBeIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided binding source &apos;{0}&apos; is a composite. &apos;{1}&apos; requires that the source must represent a single type of input..
        /// </summary>
        internal static string BindingSource_CannotBeComposite {
            get {
                return ResourceManager.GetString("BindingSource_CannotBeComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided binding source &apos;{0}&apos; is a greedy data source. &apos;{1}&apos; does not support greedy data sources..
        /// </summary>
        internal static string BindingSource_CannotBeGreedy {
            get {
                return ResourceManager.GetString("BindingSource_CannotBeGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; cache profile is not defined..
        /// </summary>
        internal static string CacheProfileNotFound {
            get {
                return ResourceManager.GetString("CacheProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate entry for library reference {0} was found. Please check that all package references in all projects use the same casing for the same package references..
        /// </summary>
        internal static string CandidateResolver_DifferentCasedReference {
            get {
                return ResourceManager.GetString("CandidateResolver_DifferentCasedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} could not be found..
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of type &apos;{0}&apos;. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, set the &apos;{1}&apos; property to a non-null value in the &apos;{2}&apos; constructor..
        /// </summary>
        internal static string ComplexTypeModelBinder_NoParameterlessConstructor_ForProperty {
            get {
                return ResourceManager.GetString("ComplexTypeModelBinder_NoParameterlessConstructor_ForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of type &apos;{0}&apos;. Model bound complex types must not be abstract or value types and must have a parameterless constructor..
        /// </summary>
        internal static string ComplexTypeModelBinder_NoParameterlessConstructor_TopLevelObject {
            get {
                return ResourceManager.GetString("ComplexTypeModelBinder_NoParameterlessConstructor_TopLevelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a model binder for model object of type &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotCreateIModelBinder {
            get {
                return ResourceManager.GetString("CouldNotCreateIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple actions matched. The following actions matched route data and had all constraints satisfied:{0}{0}{1}.
        /// </summary>
        internal static string DefaultActionSelector_AmbiguousActions {
            get {
                return ResourceManager.GetString("DefaultActionSelector_AmbiguousActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file: {0}.
        /// </summary>
        internal static string FileResult_InvalidPath {
            get {
                return ResourceManager.GetString("FileResult_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; was not rooted..
        /// </summary>
        internal static string FileResult_PathNotRooted {
            get {
                return ResourceManager.GetString("FileResult_PathNotRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type provided to &apos;{0}&apos; must implement &apos;{1}&apos;..
        /// </summary>
        internal static string FilterFactoryAttribute_TypeMustImplementIFilter {
            get {
                return ResourceManager.GetString("FilterFactoryAttribute_TypeMustImplementIFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format provided is invalid &apos;{0}&apos;. A format must be a non-empty file-extension, optionally prefixed with a &apos;.&apos; character..
        /// </summary>
        internal static string Format_NotValid {
            get {
                return ResourceManager.GetString("Format_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is invalid. Empty or null formats are not supported..
        /// </summary>
        internal static string FormatFormatterMappings_GetMediaTypeMappingForFormat_InvalidFormat {
            get {
                return ResourceManager.GetString("FormatFormatterMappings_GetMediaTypeMappingForFormat_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media types found in &apos;{0}.{1}&apos;. Add at least one media type to the list of supported media types..
        /// </summary>
        internal static string Formatter_NoMediaTypes {
            get {
                return ResourceManager.GetString("Formatter_NoMediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type &quot;{0}&quot; is not valid. MediaTypes containing wildcards (*) are not allowed in formatter mappings..
        /// </summary>
        internal static string FormatterMappings_NotValidMediaType {
            get {
                return ResourceManager.GetString("FormatterMappings_NotValidMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; cannot bind to a model of type &apos;{1}&apos;. Change the model type to &apos;{2}&apos; instead..
        /// </summary>
        internal static string FormCollectionModelBinder_CannotBindToFormCollection {
            get {
                return ResourceManager.GetString("FormCollectionModelBinder_CannotBindToFormCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        internal static string HtmlGeneration_NonPropertyValueMustBeNumber {
            get {
                return ResourceManager.GetString("HtmlGeneration_NonPropertyValueMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string HtmlGeneration_ValueIsInvalid {
            get {
                return ResourceManager.GetString("HtmlGeneration_ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number..
        /// </summary>
        internal static string HtmlGeneration_ValueMustBeNumber {
            get {
                return ResourceManager.GetString("HtmlGeneration_ValueMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encoding found for input formatter &apos;{0}&apos;. There must be at least one supported encoding registered in order for the formatter to read content..
        /// </summary>
        internal static string InputFormatterNoEncoding {
            get {
                return ResourceManager.GetString("InputFormatterNoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; must not be empty. At least one &apos;{2}&apos; is required to bind from the body..
        /// </summary>
        internal static string InputFormattersAreRequired {
            get {
                return ResourceManager.GetString("InputFormattersAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed expression of expression node type &apos;{0}&apos; is invalid. Only simple member access expressions for model properties are supported..
        /// </summary>
        internal static string Invalid_IncludePropertyExpression {
            get {
                return ResourceManager.GetString("Invalid_IncludePropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is invalid JQuery syntax because it is missing a closing bracket..
        /// </summary>
        internal static string JQueryFormValueProviderFactory_MissingClosingBracket {
            get {
                return ResourceManager.GetString("JQueryFormValueProviderFactory_MissingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required..
        /// </summary>
        internal static string KeyValuePair_BothKeyAndValueMustBePresent {
            get {
                return ResourceManager.GetString("KeyValuePair_BothKeyAndValueMustBePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is invalid. Media types which match all types or match all subtypes are not supported..
        /// </summary>
        internal static string MatchAllContentTypeIsNotAllowed {
            get {
                return ResourceManager.GetString("MatchAllContentTypeIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple overloads of method &apos;{0}&apos; are not supported..
        /// </summary>
        internal static string MiddewareFilter_ConfigureMethodOverload {
            get {
                return ResourceManager.GetString("MiddewareFilter_ConfigureMethodOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public method named &apos;{0}&apos; could not be found in the &apos;{1}&apos; type..
        /// </summary>
        internal static string MiddewareFilter_NoConfigureMethod {
            get {
                return ResourceManager.GetString("MiddewareFilter_NoConfigureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method in the type &apos;{1}&apos; must have a return type of &apos;{2}&apos;..
        /// </summary>
        internal static string MiddlewareFilter_InvalidConfigureReturnType {
            get {
                return ResourceManager.GetString("MiddlewareFilter_InvalidConfigureReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve a service of type &apos;{0}&apos; for the parameter &apos;{1}&apos; of method &apos;{2}&apos; on type &apos;{3}&apos;..
        /// </summary>
        internal static string MiddlewareFilter_ServiceResolutionFail {
            get {
                return ResourceManager.GetString("MiddlewareFilter_ServiceResolutionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find &apos;{0}&apos; in the feature list..
        /// </summary>
        internal static string MiddlewareFilterBuilder_NoMiddlewareFeature {
            get {
                return ResourceManager.GetString("MiddlewareFilterBuilder_NoMiddlewareFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property cannot be null..
        /// </summary>
        internal static string MiddlewareFilterBuilder_NullApplicationBuilder {
            get {
                return ResourceManager.GetString("MiddlewareFilterBuilder_NullApplicationBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create an instance of type &apos;{0}&apos;. The type specified in {1} must not be abstract and must have a parameterless constructor..
        /// </summary>
        internal static string MiddlewareFilterConfigurationProvider_CreateConfigureDelegate_CannotCreateType {
            get {
                return ResourceManager.GetString("MiddlewareFilterConfigurationProvider_CreateConfigureDelegate_CannotCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; must not be empty. At least one &apos;{2}&apos; is required to model bind..
        /// </summary>
        internal static string ModelBinderProvidersAreRequired {
            get {
                return ResourceManager.GetString("ModelBinderProvidersAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding context has a null Model, but this binder requires a non-null model of type &apos;{0}&apos;..
        /// </summary>
        internal static string ModelBinderUtil_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding context has a Model of type &apos;{0}&apos;, but this binder can only operate on models of type &apos;{1}&apos;..
        /// </summary>
        internal static string ModelBinderUtil_ModelInstanceIsWrong {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelInstanceIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding context cannot have a null ModelMetadata..
        /// </summary>
        internal static string ModelBinderUtil_ModelMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the &apos;{0}&apos; property was not provided..
        /// </summary>
        internal static string ModelBinding_MissingBindRequiredMember {
            get {
                return ResourceManager.GetString("ModelBinding_MissingBindRequiredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty request body is required..
        /// </summary>
        internal static string ModelBinding_MissingRequestBodyRequiredMember {
            get {
                return ResourceManager.GetString("ModelBinding_MissingRequestBodyRequiredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ModelBinding_NullValueNotValid {
            get {
                return ResourceManager.GetString("ModelBinding_NullValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for {1}..
        /// </summary>
        internal static string ModelState_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelState_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ModelState_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelState_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid..
        /// </summary>
        internal static string ModelState_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelState_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid for {0}..
        /// </summary>
        internal static string ModelState_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelState_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model&apos;s runtime type &apos;{0}&apos; is not assignable to the type &apos;{1}&apos;..
        /// </summary>
        internal static string ModelType_WrongType {
            get {
                return ResourceManager.GetString("ModelType_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route matches the supplied values..
        /// </summary>
        internal static string NoRoutesMatched {
            get {
                return ResourceManager.GetString("NoRoutesMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No page named &apos;{0}&apos; matches the supplied values..
        /// </summary>
        internal static string NoRoutesMatchedForPage {
            get {
                return ResourceManager.GetString("NoRoutesMatchedForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content-type &apos;{0}&apos; added in the &apos;{1}&apos; property is invalid. Media types which match all types or match all subtypes are not supported..
        /// </summary>
        internal static string ObjectResult_MatchAllContentType {
            get {
                return ResourceManager.GetString("ObjectResult_MatchAllContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported media type registered for output formatter &apos;{0}&apos;. There must be at least one supported media type registered in order for the output formatter to write content..
        /// </summary>
        internal static string OutputFormatterNoMediaType {
            get {
                return ResourceManager.GetString("OutputFormatterNoMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; must not be empty. At least one &apos;{2}&apos; is required to format a response..
        /// </summary>
        internal static string OutputFormattersAreRequired {
            get {
                return ResourceManager.GetString("OutputFormattersAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property of &apos;{1}&apos; must not be null..
        /// </summary>
        internal static string PropertyOfTypeCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyOfTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the &apos;{0}&apos; property is not set to true, &apos;{1}&apos; property must be specified..
        /// </summary>
        internal static string ResponseCache_SpecifyDuration {
            get {
                return ResourceManager.GetString("ResponseCache_SpecifyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input was not valid..
        /// </summary>
        internal static string SerializableError_DefaultError {
            get {
                return ResourceManager.GetString("SerializableError_DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of &apos;{0}&apos; must not be empty. Add at least one supported encoding..
        /// </summary>
        internal static string TextInputFormatter_SupportedEncodingsMustNotBeEmpty {
            get {
                return ResourceManager.GetString("TextInputFormatter_SupportedEncodingsMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of &apos;{0}&apos; must not be empty. Add at least one supported encoding..
        /// </summary>
        internal static string TextOutputFormatter_SupportedEncodingsMustNotBeEmpty {
            get {
                return ResourceManager.GetString("TextOutputFormatter_SupportedEncodingsMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported by &apos;{1}&apos;. Use &apos;{2}&apos; instead..
        /// </summary>
        internal static string TextOutputFormatter_WriteResponseBodyAsyncNotSupported {
            get {
                return ResourceManager.GetString("TextOutputFormatter_WriteResponseBodyAsyncNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method of type &apos;{1}&apos; cannot return a null value..
        /// </summary>
        internal static string TypeMethodMustReturnNotNullValue {
            get {
                return ResourceManager.GetString("TypeMethodMustReturnNotNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must derive from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeMustDeriveFromType {
            get {
                return ResourceManager.GetString("TypeMustDeriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the required services. Please add all the required services by calling &apos;{0}.{1}&apos; inside the call to &apos;{2}&apos; in the application startup code..
        /// </summary>
        internal static string UnableToFindServices {
            get {
                return ResourceManager.GetString("UnableToFindServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported content type &apos;{0}&apos;..
        /// </summary>
        internal static string UnsupportedContentType {
            get {
                return ResourceManager.GetString("UnsupportedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative page path &apos;{0}&apos; can only be used while executing a Razor Page. Specify a root relative path with a leading &apos;/&apos; to generate a URL outside of a Razor Page..
        /// </summary>
        internal static string UrlHelper_RelativePagePathIsNotSupported {
            get {
                return ResourceManager.GetString("UrlHelper_RelativePagePathIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied URL is not local. A URL with an absolute path is considered local if it does not have a host/authority part. URLs using virtual paths (&apos;~/&apos;) are also local..
        /// </summary>
        internal static string UrlNotLocal {
            get {
                return ResourceManager.GetString("UrlNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be activated by &apos;{1}&apos; because it is either a value type, an interface, an abstract class or an open generic type..
        /// </summary>
        internal static string ValueInterfaceAbstractOrOpenGenericTypesCannotBeActivated {
            get {
                return ResourceManager.GetString("ValueInterfaceAbstractOrOpenGenericTypesCannotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed because no type converter can convert between these types..
        /// </summary>
        internal static string ValueProviderResult_NoConverterExists {
            get {
                return ResourceManager.GetString("ValueProviderResult_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; requires the response cache middleware..
        /// </summary>
        internal static string VaryByQueryKeys_Requires_ResponseCachingMiddleware {
            get {
                return ResourceManager.GetString("VaryByQueryKeys_Requires_ResponseCachingMiddleware", resourceCulture);
            }
        }
    }
}
